import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body>
                <SessionProvider>
                    {children}
                    <Toaster position='bottom-right' />
                </SessionProvider>
            </body>
        </html>
    );
}
